<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecomglossary"
 *
 * Auto generated by Extension Builder 2014-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ecom Glossary',
	'description' => 'List of glossary terms with description.',
	'category' => 'plugin',
	'author' => 'Nicolas Scheidler',
	'author_email' => 'nicolas.scheidler@ecom-ex.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.6.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'php' => '5.4.0-5.5.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);